#cloud-config

package_update: true

packages:
  - mariadb-server
  - nano

runcmd:
  - sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
  - cat >> /tmp/db.sql << EOF
    CREATE DATABASE msb_rec;
    GRANT ALL PRIVILEGES ON msb_rec.* TO "udber168"@"%" IDENTIFIED BY "eqrv4azeq86f_tf";
    FLUSH PRIVILEGES;
    EOF
  - mysql < /tmp/db.sql
  - systemctl restart mariadb
  - systemctl enable mariadb

final_message: "The system is finally up Charlie ! After $UPTIME seconds"
