#cloud-config

package_update: true

packages:
  - apache2
  - php8.4-fpm
  - libapache2-mod-php
  - php8.4-mysql
  - php8.4-curl
  - php8.4-gd
  - php8.4-mbstring
  - php8.4-xml
  - php8.4-xmlrpc
  - php8.4-soap
  - php8.4-intl
  - php8.4-zip
  - php8.4-xdebug
  - php8.4-ssh2
  - certbot
  - python3-certbot-apache
  - nano
  - unzip


runcmd:
  - wget -O /tmp/wordpress.tar.gz https://wordpress.org/latest.tar.gz
  - mkdir /var/cuisine/recette.monsiegedebureau.fr/public
  - tar -xzvf /tmp/wordpress.tar.gz -C /var/cuisine/recette.monsiegedebureau.fr/public
  - chown -R www-data:www-data /var/cuisine/recette.monsiegedebureau.fr
  - cat >> /etc/apache2/sites-available/recette.monsiegedebureau.fr.conf << EOF
    <VirtualHost *:80>
    ServerAdmin recette+msb@latelier62.fr
    ServerName recette.monsiegedebureau.fr
    ServerAlias www.recette.monsiegedebureau.fr
    # Redirect www to ${siteName} # OU l'inverse - modifier suivant le besoin.
    RewriteCond %{SERVER_NAME} =www.recette.monsiegedebureau.fr
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
    
    DocumentRoot /var/cuisine/recette.monsiegedebureau.fr/public
    
    # Custom log files, to differentiate from root server
    ErrorLog ${APACHE_LOG_DIR}/error-recette.monsiegedebureau.fr.log
    CustomLog ${APACHE_LOG_DIR}/access-recette.monsiegedebureau.fr.log combined
    LogLevel crit
    
    Alias /wp-content /var/cuisine/recette.monsiegedebureau.fr/public/wp-content
    
    <Directory /var/cuisine/recette.monsiegedebureau.fr/public>
    Options FollowSymLinks
    AllowOverride Limit Options FileInfo
    DirectoryIndex index.php
    Require all granted
    #          <FilesMatch ".php$">
    #           SetHandler "proxy:unix:/var/run/php/php8.2-fpm.${phpPoolUser}.sock|fcgi://localhost/"
    #        </FilesMatch>
    </Directory>
    <Directory /var/cuisine/recette.monsiegedebureau.fr/public/wp-content>
    Options FollowSymLinks
    Require all granted
    </Directory>
    </VirtualHost>
    EOF
  - a2dissite 000-default
  - a2ensite recette.monsiegedebureau.fr.conf
  - systemctl enable apache2
  - systemctl restart apache2
  # CERTBOT Ã  faire une fois que le DNS est basculÃ©
  # - certbot -n --apache --agree-tos --redirect --hsts --uir --staple-ocsp --email admin+web62@latelier62.fr -d demo.domain.tld -v

final_message: "The system is finally up Charlie. After $UPTIME seconds. Don't forget CERTBOT and PHP."